
import 'package:sift_loan/feature/auth/domain/entities/account_sumary.dart';
import 'package:sift_loan/core/constants/dummy.dart';

class AccountSummaryModel extends AccountSummaryDetails {
  const AccountSummaryModel({
    required super.accountName,
    required super.accountNumber,
    required super.accountOpenDate,
    required super.accountStatus,
    required super.accountOpeningBalance,
    required super.amountBlocked,
    required super.amtOdLimit,
    required super.availableBalance,
    required super.branchAddress,
    required super.branchCity,
    required super.branchCode,
    required super.branchName,
    required super.branchState,
    required super.bvn,
    required super.clearedBalance,
    required super.closingBalance,
    required super.currencyCode,
    required super.currencyName,
    required super.customerId,
    required super.hasCOT,
    required super.hasImage,
    required super.isStaff,
    required super.loanStatus,
    required super.lodgement,
    required super.netBalance,
    required super.productCode,
    required super.productCodeDesc,
    required super.totalBalance,
    required super.unclearedBalance,
    required super.withdrawal,
    required super.customerSegment,
    required super.hasFixedDeposit,
    required super.tier,
    required super.accountClassType,
    required super.customerType,
  });

  factory AccountSummaryModel.fromJson(Map<String, dynamic> json) {
    return AccountSummaryModel(
      accountName: json['accountName'],
      accountNumber: json['accountNo'],
      accountOpenDate: json['accountOpenDate'] ?? '',
      accountStatus: json['accountStatus'] ?? '',
      accountOpeningBalance: json['acctOpeningBalance'] ?? 0.0,
      amountBlocked: json['amountBlocked'] ?? 0.0,
      amtOdLimit: json['amt_od_limit'],
      availableBalance: json['availableBalance'],
      branchAddress: json['branchAddress'] ?? '',
      branchCity: json['branchCity'] ?? '',
      branchCode: json['branchCode'] ?? '',
      branchName: json['branchName'] ?? '',
      branchState: json['branchState'] ?? '',
      bvn: json['bvn'] ?? '',
      clearedBalance: json['clearedBalance'] ?? 0.0,
      closingBalance: json['closingBalance'] ?? 0.0,
      currencyCode: json['currencyCode'] ?? '',
      currencyName: json['currencyName'] ?? '',
      customerId: json['custID'] ?? '',
      hasCOT: json['hasCOT'] ?? 0,
      hasImage: json['hasImage'] ?? 0,
      isStaff: json['isStaff'] ?? '',
      loanStatus: json['loanStatus'] ?? '',
      lodgement: json['lodgement'] ?? 0.0,
      netBalance: json['netBalance'] ?? 0.0,
      productCode: json['productCode'] ?? '',
      productCodeDesc: json['productCodeDesc'] ?? '',
      totalBalance: json['totalBalance'] ?? 0.0,
      unclearedBalance: json['unclearedBalance'] ?? 0.0,
      withdrawal: json['withdrawal'] ?? 0.0,
      customerSegment: json['customerSegment'] ?? '',
      hasFixedDeposit: json['hasFixedDeposit'] ?? '',
      tier: json['tier'] ?? '',
      accountClassType: json['ac_class_type'] ?? '',
      customerType: json['customer_type'] ?? '',
    );
  }

  factory AccountSummaryModel.dummy() {
    return AccountSummaryModel(
        accountName: "Tunde Chukwuma Mohammed",
        accountNumber: Dummy.defaultAccountNumber.toString(),
        accountOpenDate: "dummy open date",
        accountStatus: "dummy account status",
        accountOpeningBalance: 0,
        amountBlocked: 0,
        amtOdLimit: 0,
        availableBalance: 10000,
        branchAddress: "address",
        branchCity: "city",
        branchCode: "code",
        branchName: "name",
        branchState: "state",
        bvn: "bvn",
        clearedBalance: 0,
        closingBalance: 0,
        currencyCode: "NGN",
        currencyName: "currency name",
        customerId: "1",
        hasCOT: 1,
        hasImage: 1,
        isStaff: "F",
        loanStatus: "F",
        lodgement: 0,
        netBalance: 0,
        productCode: "product code",
        productCodeDesc: "productCodeDesc",
        totalBalance: 0,
        unclearedBalance: 0,
        withdrawal: 0,
        customerSegment: 'customerSegment',
        hasFixedDeposit: "F",
        tier: "tier",
        accountClassType: "accountClassType",
        customerType: "customerType");
  }

  AccountSummaryModel copyWith({
    String? accountName,
    String? accountNumber,
    String? currencyCode,
    String? currencyName,
  }) {
    return AccountSummaryModel(
      accountName: accountName ?? this.accountName,
      accountNumber: accountNumber ?? this.accountNumber,
      accountOpenDate: "dummy open date",
      accountStatus: "dummy account status",
      accountOpeningBalance: 0,
      amountBlocked: 0,
      amtOdLimit: 0,
      availableBalance: 10000,
      branchAddress: "address",
      branchCity: "city",
      branchCode: "code",
      branchName: "name",
      branchState: "state",
      bvn: "bvn",
      clearedBalance: 0,
      closingBalance: 0,
      currencyCode: currencyCode ?? "NGN",
      currencyName: currencyName ?? "Nigerian Naira",
      customerId: "1",
      hasCOT: 1,
      hasImage: 1,
      isStaff: "F",
      loanStatus: "F",
      lodgement: 0,
      netBalance: 0,
      productCode: "product code",
      productCodeDesc: "productCodeDesc",
      totalBalance: 0,
      unclearedBalance: 0,
      withdrawal: 0,
      customerSegment: 'customerSegment',
      hasFixedDeposit: "F",
      tier: "tier",
      accountClassType: "accountClassType",
      customerType: "customerType",
    );
  }
}
